CREATE TABLE IF NOT EXISTS "Tickets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Status" integer NOT NULL,
    "Priority" integer NOT NULL,
    "Assignee" character varying(120) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id")
);
