CREATE TABLE IF NOT EXISTS "ApplicationUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(320) NOT NULL,
    "NormalizedEmail" character varying(320) NOT NULL,
    "DisplayName" character varying(120) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ApplicationUsers" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ApplicationUsers_NormalizedEmail"
    ON "ApplicationUsers" ("NormalizedEmail");
